// Student Info App

// Taking input from user
let name = prompt("Enter your name:");
let age = prompt("Enter your age:");
let course = prompt("Enter your course name:");

// Display details in console
console.log("----- Student Details -----");
console.log("Name   : " + name);
console.log("Age    : " + age);
console.log("Course : " + course);

// Show details in alert popup
alert(
  "Student Details:\n" +
  "Name: " + name + "\n" +
  "Age: " + age + "\n" +
  "Course: " + course
);
